version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - my_net
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 10s
      retries: 5

  server:
    container_name: server
    build: ./
    volumes:
      - ./files/:/server/files/
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my_net

networks:
  my_net:
