version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - my_net

  server:
    container_name: server
    build: ./
    env_file:
      - .env
    ports:
      - 18080:18080
    depends_on:
      - postgres
    networks:
      - my_net

networks:
  my_net: